apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrp-wiremock-server-deployment

spec:
  selector:
    matchLabels:
      app: services-menu
  replicas: 1
  template:
    metadata:
      labels:
        app: services-wiremock
    spec:
      containers:
        - name: services-wiremock
          image: ngrpdevregistry.azurecr.io/ngrp-wiremock-server:#{Build.BuildId}#
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 300
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: ngrp-wiremock-server-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "#{INTERNAL-LOAD-BALANCER}#"
spec:
  selector:
    app: services-wiremock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: #{EXT-ACCESS-SERVICE-TYPE}#