apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrp-wiremock-server-deployment

spec:
  selector:
    matchLabels:
      app: services-wiremock
  replicas: 1
  template:
    metadata:
      labels:
        app: services-wiremock
    spec:
      containers:
        - name: services-wiremock
          image: ngrpdevregistry.azurecr.io/ngrp-wiremock-server:3
          livenessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 300
          ports:
            - containerPort: 8080
            - containerPort: 8443
      imagePullSecrets:
        - name: regcred
---
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
kind: Service
apiVersion: v1
metadata:
  name: ngrp-wiremock-server-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  selector:
    app: services-wiremock
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 8443
      targetPort: 8443
  type: LoadBalancer